---
version: '3.3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  resque_web:
    image: rescue_web
    build:
      context: .
      dockerfile: Dockerfile.resque_web
    depends_on:
      - redis
    ports:
      - 5678:5678
    environment:
      - RESQUE_WEB_REDIS=redis:6379
    volumes:
      - rescue-web-data:/data

  web:
    image: influencer_orders
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 9393:9393
    volumes:
      - app-output:/tmp

  worker:
    image: influencer_orders
    command: ["shotgun"]
    depends_on:
      - redis
    volumes:
      - app-output:/tmp
    env_file: .env
    environment:
      - QUEUE=*
    command: ["rake", "resque:work"]
    deploy:
      replicas: 5

  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  app-output:
  rescue-web-data:
  postgres-data:

