---
development:
  adapter: postgresql
  database: development
  host: localhost
  port: 5432
  user: postgres
  password: postgres

testing:
  adapter: postgresql
  database: testing
  host: localhost
  port: 5432
  user: postgres
  password: postgres

production:
  adapter: postgresql
  database: production
  host: localhost
  port: 5432
  user: postgres
  password: postgres
